const $=id=>document.getElementById(id);
const providers=['lumiere','imdb','tvdb','simkl','tmdb','mdblist'];
const names={lumiere:'Lumiere DB',imdb:'IMDb',tvdb:'TVDB',simkl:'SIMKL',tmdb:'TMDB',mdblist:'MDBList'};
const colors={lumiere:'#26ccc2',imdb:'#f5c747',tvdb:'#60c584',simkl:'#a086eb',tmdb:'#5caef0',mdblist:'#fa8582'};
const categories={exact:'Exact title',typo:'Typo',year:'With year',format:'Punctuation',partial:'Partial title',abbreviation:'Abbreviation',alias:'Alias',franchise:'Franchise',negative:'No-match control'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const median=a=>{a=[...a].sort((a,b)=>a-b);return a.length?(a[Math.floor((a.length-1)/2)]+a[Math.ceil((a.length-1)/2)])/2:null};
const params=new URLSearchParams(location.search);let media=['movie','series','both'].includes(params.get('media'))?params.get('media'):'both',page=0,observations=[],visible=[];
$('category').innerHTML+=Object.entries(categories).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
if(categories[params.get('category')])$('category').value=params.get('category');
if(['1','5','10'].includes(params.get('top')))$('cutoff').value=params.get('top');
if(['all','nonempty','matched'].includes(params.get('timing')))$('timing').value=params.get('timing');
function matches(r){return r.valid_response&&r.target_rank!==null&&r.target_rank<=Number($('cutoff').value)}
function selected(ignoreCategory=false){return observations.filter(r=>(media==='both'||r.media_type===media)&&(ignoreCategory||$('category').value==='all'||r.category===$('category').value))}
function remember(){const p=new URLSearchParams({media,category:$('category').value,top:$('cutoff').value,timing:$('timing').value});history.replaceState(null,'',`${location.pathname}?${p}${location.hash}`)}
function bar(label,value,max,color,display,title){return `<div class="bar-row" tabindex="0" title="${esc(title)}" aria-label="${esc(title)}"><span>${esc(label)}</span><div class="track"><span class="fill" style="width:${max?Math.max(0,Math.min(100,value/max*100)):0}%;background:${color}"></span></div><span class="value">${display}</span></div>`}
function render(){remember();document.querySelectorAll('[data-media]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.media===media)));const rs=selected();$('search-count').textContent=rs.length;$('request-count').textContent=rs.reduce((s,r)=>s+r.outbound_calls,0);const scored=rs.filter(r=>r.reviewed_title_case);$('accuracy').innerHTML=providers.map(p=>{const a=scored.filter(r=>r.provider===p),n=a.filter(matches).length,u=a.some(r=>r.unresolved_top5);return bar(names[p],n,a.length,colors[p],a.length?`${n} / ${a.length}${u?'*':''}`:'—',`${names[p]}: ${n} confirmed matches in ${a.length} reviewed queries${u?'; contains unresolved identifiers':''}`)}).join('');$('accuracy-note').textContent=scored.length?'*Unmapped identifiers may hide a match. Alias, franchise and no-match controls are excluded.':'This category needs relevance review and is excluded from title accuracy. Explore its returned results below.';
const timeRows=providers.map(p=>{let a=rs.filter(r=>r.provider===p);if($('timing').value==='nonempty')a=a.filter(r=>r.count>0);if($('timing').value==='matched')a=a.filter(r=>r.reviewed_title_case&&matches(r));return {p,a,m:median(a.map(r=>r.ms))}});const max=Math.max(1,...timeRows.map(x=>x.m||0));$('latency').innerHTML=timeRows.map(({p,a,m})=>bar(names[p],m||0,max,colors[p],m===null?'—':`${Math.round(m)} ms`,a.length?`${names[p]}: median ${Math.round(m)} ms; n=${a.length}; range ${Math.round(Math.min(...a.map(r=>r.ms)))}–${Math.round(Math.max(...a.map(r=>r.ms)))} ms`:`${names[p]}: no eligible responses`)).join('');
const cats=['exact','typo','year','format','partial','abbreviation'];$('heatmap').innerHTML=`<table class="heat"><thead><tr><th>Provider</th>${cats.map(c=>`<th><button data-category="${c}" title="Filter ${categories[c]}">${({exact:'Exact',typo:'Typo',year:'Year',format:'Punct.',partial:'Partial',abbreviation:'Abbrev.'})[c]}</button></th>`).join('')}</tr></thead><tbody>${providers.map(p=>`<tr><th>${names[p]}</th>${cats.map(c=>{const a=selected(true).filter(r=>r.provider===p&&r.category===c&&r.reviewed_title_case),n=a.filter(matches).length;return `<td style="background:rgba(38,204,194,${a.length?.05+.47*n/a.length:0})" title="${esc(`${categories[c]}: ${n} of ${a.length} confirmed matches`)}">${a.length?`${n}/${a.length}${a.some(r=>r.unresolved_top5)?'*':''}`:'—'}</td>`}).join('')}</tr>`).join('')}</tbody></table>`;
renderRequests(rs);page=0;renderTable();}
function renderRequests(rs){const services=[...new Set(rs.flatMap(r=>Object.keys(r.outbound_by_service)))].sort();const palette=['#26ccc2','#f5c747','#5caef0','#a086eb','#fa8582','#60c584','#d7a4d2','#95aab9'];const color=s=>({Lumiere:colors.lumiere,IMDb:colors.imdb,TVDB:colors.tvdb,SIMKL:colors.simkl,TMDB:colors.tmdb,MDBList:colors.mdblist}[s]||'#95aab9');$('legend').innerHTML=services.map(s=>`<span><i style="background:${color(s)}"></i>${esc(s)}</span>`).join('');const totals=providers.map(p=>rs.filter(r=>r.provider===p).reduce((s,r)=>s+r.outbound_calls,0));const max=Math.max(1,...totals);$('requests').innerHTML=providers.map((p,i)=>{const counts={};rs.filter(r=>r.provider===p).forEach(r=>Object.entries(r.outbound_by_service).forEach(([s,n])=>counts[s]=(counts[s]||0)+n));const title=`${names[p]}: ${Object.entries(counts).map(([s,n])=>`${s} ${n}`).join(', ')}; total ${totals[i]}`;return `<div class="bar-row" tabindex="0" title="${esc(title)}" aria-label="${esc(title)}"><span>${names[p]}</span><div class="track">${services.map(s=>`<span class="stack" style="background:${color(s)};width:${(counts[s]||0)/max*100}%"></span>`).join('')}</div><span class="value">${totals[i]} calls</span></div>`}).join('')}
function renderTable(){const q=$('query-search').value.toLowerCase();visible=selected().filter(r=>(r.query+' '+r.provider_label).toLowerCase().includes(q));const sort=$('sort').value;visible.sort((a,b)=>sort==='slow'?b.ms-a.ms:sort==='calls'?b.outbound_calls-a.outbound_calls:sort==='provider'?a.provider_label.localeCompare(b.provider_label)||a.query.localeCompare(b.query):a.query.localeCompare(b.query)||a.provider_label.localeCompare(b.provider_label));const pages=Math.max(1,Math.ceil(visible.length/12));page=Math.min(page,pages-1);$('row-count').textContent=`${visible.length} search observations`;$('rows').innerHTML=visible.slice(page*12,page*12+12).map((r,i)=>`<tr><td><button class="query-link" data-row="${page*12+i}">${esc(r.query)}</button></td><td><span class="provider-dot" style="background:${colors[r.provider]}"></span>${esc(r.provider_label)}</td><td>${r.media_type==='movie'?'Movie':'Show'} · ${categories[r.category]||esc(r.category)}</td><td>${!r.reviewed_title_case?'Review pending':r.target_rank??(r.unresolved_top5?'Unresolved':'Not found')}</td><td>${Math.round(r.ms)} ms</td><td>${r.outbound_calls}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching searches. Try a different filter.</td></tr>';$('page').textContent=`${page+1} / ${pages}`;$('prev').disabled=page===0;$('next').disabled=page===pages-1;}
function detail(r){$('detail-content').innerHTML=`<h2>${esc(r.query)}</h2><p>${esc(r.provider_label)} · ${r.media_type==='movie'?'Movie':'Show'} · ${categories[r.category]}</p><p>${Math.round(r.ms)} ms · ${r.count} results · ${r.outbound_calls} outbound HTTP attempts</p><p>${r.reviewed_title_case?`Expected title rank: ${r.target_rank??'not confirmed'}${r.unresolved_top5?' (contains unresolved IDs)':''}`:'Exploratory case: relevance review pending.'}</p><p>Cache cohort: ${r.cohort?'after coordinated restart':'initial process'}. ${r.http_error_calls?`${r.http_error_calls} downstream HTTP error(s).`:''}</p><h3>Returned titles</h3><ol>${r.results.map(x=>`<li>${esc(x.name)} <small>${esc(x.year)} · ${esc(x.id)}</small></li>`).join('')||'<li>No results</li>'}</ol><h3>Request destinations</h3><p>${Object.entries(r.outbound_by_service).map(([s,n])=>`${esc(s)}: ${n}`).join(' · ')||'None observed'}</p><details><summary>Observed stage durations</summary><p>These intervals overlap and are not additive or feature-off estimates.</p>${Object.entries(r.stage_union_ms||{}).map(([s,n])=>`<p>${esc(s.replaceAll('_',' '))}: ${Math.round(n)} ms</p>`).join('')}</details>`;$('detail').showModal();}
document.querySelectorAll('[data-media]').forEach(b=>b.addEventListener('click',()=>{media=b.dataset.media;render()}));['category','cutoff','timing'].forEach(id=>$(id).addEventListener('change',render));['query-search','sort'].forEach(id=>$(id).addEventListener(id==='sort'?'change':'input',()=>{page=0;renderTable()}));$('prev').onclick=()=>{page--;renderTable()};$('next').onclick=()=>{page++;renderTable()};$('heatmap').onclick=e=>{const b=e.target.closest('[data-category]');if(b){$('category').value=b.dataset.category;render()}};$('rows').onclick=e=>{const b=e.target.closest('[data-row]');if(b)detail(visible[Number(b.dataset.row)])};$('close-detail').onclick=()=>$('detail').close();$('detail').onclick=e=>{if(e.target===$('detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};
try{const response=await fetch('data/benchmark.json');if(!response.ok)throw Error('HTTP '+response.status);observations=(await response.json()).observations;render()}catch(error){$('accuracy').innerHTML='<p role="alert">The dataset could not load. Please reload or read the linked report.</p>';console.error(error)}
