import {runs,categories,median,hit,outcome,select,timingRows,combine} from './model.mjs';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);
const state={media:['both','movie','series'].includes(params.get('media'))?params.get('media'):'both',category:categories[params.get('category')]?params.get('category'):'all',cutoff:['1','5','10'].includes(params.get('top'))?Number(params.get('top')):params.get('top')==='all'?Infinity:5,timing:['all','nonempty','matched','common'].includes(params.get('timing'))?params.get('timing'):'all',providers:new Set(params.has('runs')?params.get('runs').split(',').filter(x=>runs.some(r=>r[0]===x)):runs.map(r=>r[0])),tab:['overview','queries','notes'].includes(location.hash.slice(1))?location.hash.slice(1):'overview'};
let rows=[],page=0,ready=false;
const run=p=>runs.find(r=>r[0]===p), chosen=()=>runs.filter(r=>state.providers.has(r[0]));
const format=n=>n===null?'—':Math.round(n).toLocaleString('en-US');
const pct=(n,d)=>d?`${Math.round(n/d*100)}%`:'—';
function remember(){const p=new URLSearchParams({media:state.media,category:state.category,top:state.cutoff===Infinity?'all':state.cutoff,timing:state.timing,runs:[...state.providers].join(',')});history.replaceState(null,'',`${location.pathname}?${p}#${state.tab}`)}
function tab(name){state.tab=name;document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('.tabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===name)));remember();}
function chars(value,max,n=24){const count=max?Math.min(n,Math.max(0,Math.round(value/max*n))):0;return `<span aria-hidden="true">${'█'.repeat(count)}<span class="ascii-empty">${'░'.repeat(n-count)}</span></span>`;}
function bar(p,value,max,label,action,title){const [,name,color]=run(p);return `<button class="bar" style="--run:${color}" data-action="${action}" data-provider="${p}" aria-label="${esc(name+': '+title)}"><span class="bar-name">${name}</span><span class="ascii-track">${chars(value,max)}</span><span class="bar-value">${label}</span></button>`;}
function render(){
 if(!ready)return;
 remember();const selected=select(rows,state),timed=timingRows(selected,state),providers=chosen();
 $('status').textContent=`[OK] ${selected.length} observations · ${providers.length} runs · ${new Set(selected.map(r=>r.case_id)).size} queries · ${selected.reduce((s,r)=>s+r.outbound_calls,0)} HTTP attempts / saved snapshot`;
 document.querySelectorAll('[data-media]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.media===state.media)));
 $('accuracy').innerHTML=providers.map(([p])=>{const a=selected.filter(r=>r.provider===p&&r.reviewed_title_case),n=a.filter(r=>hit(r,state.cutoff)).length;return bar(p,n,a.length,a.length?`${n}/${a.length}${a.some(r=>r.unresolved_top5)?'*':''}`:'n/a','quality',`${n} confirmed of ${a.length} scored; inspect queries`)}).join('')||'<p class="empty">Select a provider run above.</p>';
 const medians=providers.map(([p])=>median(timed.filter(r=>r.provider===p).map(r=>r.ms))),max=Math.max(1,...medians.filter(n=>n!==null));
 $('latency').innerHTML=providers.map(([p],i)=>{const a=timed.filter(r=>r.provider===p);return bar(p,medians[i]||0,max,`${format(medians[i])}${a.length?' ms':''}`,'timing',`median ${format(medians[i])} ms, n=${a.length}; inspect queries`)}).join('')+(providers.length&&!timed.length?'<p class="empty">No responses meet this timing selection. Try a broader sample or fewer provider runs.</p>':'');
 const totals=providers.map(([p])=>selected.filter(r=>r.provider===p).reduce((s,r)=>s+r.outbound_calls,0));
 $('requests').innerHTML=providers.map(([p],i)=>bar(p,totals[i],Math.max(1,...totals),`${totals[i]} calls`,'requests',`${totals[i]} downstream attempts; inspect services`)).join('');
 distribution(timed,providers);coverage(selected,providers);matrix(providers);explorer();
}
function distribution(timed,providers){
 const max=Math.max(1,...timed.map(r=>r.ms));
 $('distribution').innerHTML=`<div class="axis"><span>0 ms</span><span>${format(max/2)} ms</span><span>${format(max)} ms</span></div>`+providers.map(([p,name,color])=>{const a=timed.filter(r=>r.provider===p);return `<div class="dist-row" style="--run:${color}"><span class="dist-label">${name}</span><div class="dist-plot">${a.map((r,i)=>`<button class="dot" data-row="${r.index}" style="left:${r.ms/max*100}%;top:${(i%3)*8}px" title="${esc(r.query)} · ${format(r.ms)} ms" aria-label="${esc(name+' / '+r.query)}: ${format(r.ms)} ms. Inspect search">⠿</button>`).join('')}</div><span class="dist-count">n=${a.length}</span></div>`}).join('');
}
function coverage(selected,providers){const fields=['description','poster','background','trailers'];$('coverage').innerHTML=`<table><thead><tr><th>Run</th><th>Entries</th>${fields.map(f=>`<th>${f==='description'?'Text':f}</th>`).join('')}</tr></thead><tbody>${providers.map(([p,name,color])=>{const items=selected.filter(r=>r.provider===p).flatMap(r=>r.results);return `<tr><td style="color:${color}">${name}</td><td>${items.length}</td>${fields.map(f=>`<td>${pct(items.filter(x=>x[f]).length,items.length)}</td>`).join('')}</tr>`}).join('')}</tbody></table>`}
function matrix(providers){const cs=['exact','typo','year','format','partial','abbreviation'],base=select(rows,state,true);$('matrix').innerHTML=`<table><thead><tr><th>Run</th>${cs.map(c=>`<th>${categories[c]}</th>`).join('')}</tr></thead><tbody>${providers.map(([p,name,color])=>`<tr><td style="color:${color}">${name}</td>${cs.map(c=>{const a=base.filter(r=>r.provider===p&&r.category===c&&r.reviewed_title_case),n=a.filter(r=>hit(r,state.cutoff)).length;return `<td><button class="matrix-cell" style="--run:${color}" data-action="category" data-category="${c}" data-provider="${p}" aria-label="${esc(name+' / '+categories[c])}: ${n} of ${a.length}. Inspect queries">${a.length?`${n}/${a.length}${a.some(r=>r.unresolved_top5)?'*':''}`:'—'} <span class="dim" aria-hidden="true">${a.length?'▰'.repeat(n)+'▱'.repeat(a.length-n):''}</span></button></td>`}).join('')}</tr>`).join('')}</tbody></table>`}
function target(r){return r.expected_targets?.length?r.expected_targets.map(t=>`${t.name}${t.year?' ('+t.year+')':''}`).join('; '):r.supplemental_review?.scope||'No expected title'}
function explorer(){
 const q=$('search').value.trim().toLowerCase(),selected=select(rows,state).filter(r=>r.query.toLowerCase().includes(q));
 const groups=[...new Set(selected.map(r=>r.case_id))].map(id=>selected.filter(r=>r.case_id===id));
 groups.sort((a,b)=>$('sort').value==='slow'?Math.max(...b.map(r=>r.ms))-Math.max(...a.map(r=>r.ms)):$('sort').value==='calls'?b.reduce((s,r)=>s+r.outbound_calls,0)-a.reduce((s,r)=>s+r.outbound_calls,0):a[0].query.localeCompare(b[0].query));
 const size=$('page-size').value==='all'?Math.max(1,groups.length):Number($('page-size').value),pages=Math.max(1,Math.ceil(groups.length/size));page=Math.max(0,Math.min(page,pages-1));
 const slice=groups.slice(page*size,(page+1)*size),providers=chosen();
 $('explorer').innerHTML=groups.length?`<table><thead><tr><th>Query / target</th>${providers.map(([,name,color])=>`<th style="color:${color}">${name}</th>`).join('')}</tr></thead><tbody>${slice.map(g=>`<tr><td>${esc(g[0].query)}<span class="query-meta">${g[0].media_type==='movie'?'Movie':'Show'} / ${categories[g[0].category]}</span><span class="target">${esc(target(g[0]))}</span></td>${providers.map(([p])=>{const r=g.find(x=>x.provider===p);if(!r)return '<td>—</td>';const o=outcome(r,state.cutoff);return `<td><button data-row="${r.index}" aria-label="${esc(run(p)[1]+' / '+r.query+' / '+o.label)}"><span class="cell-code ${o.tone}">${esc(o.label)}</span><span class="cell-code">${format(r.ms)} ms</span><span class="query-meta">${r.outbound_calls} HTTP · ${r.count} results</span></button></td>`}).join('')}</tr>`).join('')}</tbody></table>`:'<p class="empty">No matching queries. Adjust the search or filters above.</p>';
 $('page-info').textContent=groups.length?`${page*size+1}–${Math.min((page+1)*size,groups.length)} of ${groups.length} queries · ${selected.length} observations`:'0 queries';$('prev').disabled=page===0;$('next').disabled=page>=pages-1;$('explorer').scrollTop=0;
}
function open(html){$('detail-body').innerHTML=html;if(!$('detail').open)$('detail').showModal();$('detail').scrollTop=0;}
function list(p,kind,category){let a=select(rows,state).filter(r=>r.provider===p),title=run(p)[1],note='';
 if(kind==='quality'){a=a.filter(r=>r.reviewed_title_case);title+=' / title discovery';note='Confirmed matches at the selected cutoff. Unresolved IDs may hide a match.';}
 if(kind==='timing'){a=timingRows(select(rows,state),state).filter(r=>r.provider===p);title+=' / response time';note='The exact queries included in the selected timing population.';}
 if(kind==='category'){a=select(rows,state,true).filter(r=>r.provider===p&&r.category===category&&r.reviewed_title_case);title+=' / '+categories[category];note='Uses the current media and cutoff; ignores the category filter.';}
 let services='';if(kind==='requests'){title+=' / downstream requests';const counts={};a.forEach(r=>Object.entries(r.outbound_by_service||{}).forEach(([s,n])=>counts[s]=(counts[s]||0)+n));services='<h3>Service breakdown</h3>'+Object.entries(counts).map(([s,n])=>`<p>${esc(s)} <span class="good">${n} attempts</span></p>`).join('');note='Includes search and enrichment attempts, including failures.';}
 open(`<h2 id="detail-title">${title}</h2><p class="caption">${note}</p>${services}<div class="table-scroll"><table><thead><tr><th>Query</th><th>Outcome</th><th>Time</th><th>HTTP</th></tr></thead><tbody>${a.map(r=>{const o=outcome(r,state.cutoff);return `<tr><td><button data-row="${r.index}">${esc(r.query)} →</button></td><td class="${o.tone}">${esc(o.label)}</td><td>${format(r.ms)} ms</td><td>${r.outbound_calls}</td></tr>`}).join('')||'<tr><td colspan="4">No eligible searches.</td></tr>'}</tbody></table></div>`);
}
function detail(r){const o=outcome(r,state.cutoff);open(`<h2 id="detail-title">${esc(r.query)}</h2><p class="caption">${run(r.provider)[1]} / ${r.media_type==='movie'?'Movie':'Show'} / ${categories[r.category]}</p><p>Target: ${esc(target(r))}</p><div class="metrics"><div><strong class="${o.tone}">${esc(o.label)}</strong><span>at ${state.cutoff===Infinity?'any saved position':'top '+state.cutoff}</span></div><div><strong>${format(r.ms)} ms</strong><span>complete response</span></div><div><strong>${r.outbound_calls}</strong><span>HTTP attempts</span></div><div><strong>${r.count}</strong><span>returned results</span></div></div>${r.unresolved_top5?'<p class="warn">Unmapped native IDs in the first five results may hide a target match.</p>':''}<h3>Returned titles / all saved results</h3><div class="table-scroll"><table class="result-table"><thead><tr><th>#</th><th>Title</th><th>Year</th><th>ID</th><th>Text</th><th>Poster</th><th>Backdrop</th><th>Trailer</th></tr></thead><tbody>${r.results.map(x=>`<tr><td>${x.rank}</td><td>${esc(x.name)}${(r.expected_targets||[]).some(t=>t.id===x.id)?' <span class="good">[target]</span>':''}</td><td>${esc(x.year)}</td><td>${esc(x.id)}</td>${['description','poster','background','trailers'].map(f=>`<td class="${x[f]?'good':'muted'}">${x[f]?'yes':'—'}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="8">Empty response. No returned titles.</td></tr>'}</tbody></table></div><h3>Downstream requests</h3><p>${Object.entries(r.outbound_by_service||{}).map(([s,n])=>`${esc(s)}: ${n}`).join(' · ')||'None recorded'} · ${r.http_error_calls||0} HTTP errors</p><h3>Observed stage durations</h3><p class="caption">Overlapping intervals. These cannot be added or subtracted to predict a feature-off response.</p><table><tbody>${Object.entries(r.stage_union_ms||{}).map(([s,n])=>`<tr><td>${esc(s.replaceAll('_',' '))}</td><td>${format(n)} ms</td></tr>`).join('')}</tbody></table>`)}
$('category').innerHTML+=Object.entries(categories).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
function sync(){ $('category').value=state.category;$('cutoff').value=state.cutoff===Infinity?'all':state.cutoff;$('timing').value=state.timing;$('runs').innerHTML=runs.map(([p,name,color])=>`<label style="--run:${color}"><input type="checkbox" value="${p}" ${state.providers.has(p)?'checked':''}>${name}</label>`).join('');}
sync();tab(state.tab);
$('runs').onchange=e=>{e.target.checked?state.providers.add(e.target.value):state.providers.delete(e.target.value);page=0;render()};
$('category').onchange=e=>{state.category=e.target.value;page=0;render()};$('cutoff').onchange=e=>{state.cutoff=e.target.value==='all'?Infinity:Number(e.target.value);render()};$('timing').onchange=e=>{state.timing=e.target.value;render()};
$('search').oninput=()=>{page=0;explorer()};$('sort').onchange=$('page-size').onchange=()=>{page=0;explorer()};$('prev').onclick=()=>{page--;explorer()};$('next').onclick=()=>{page++;explorer()};$('close').onclick=()=>$('detail').close();
$('reset').onclick=()=>{Object.assign(state,{media:'both',category:'all',cutoff:5,timing:'all',providers:new Set(runs.map(r=>r[0]))});$('search').value='';$('sort').value='title';$('page-size').value='6';page=0;sync();render()};
document.addEventListener('click',e=>{const t=e.target.closest('[data-tab]'),m=e.target.closest('[data-media]'),r=e.target.closest('[data-row]'),a=e.target.closest('[data-action]');if(t)tab(t.dataset.tab);if(m){state.media=m.dataset.media;page=0;render()}if(r)detail(rows[Number(r.dataset.row)]);if(a)list(a.dataset.provider,a.dataset.action,a.dataset.category)});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.target.closest('input,select,textarea,dialog')){e.preventDefault();tab('queries');$('search').focus()}});
try{const responses=await Promise.all([fetch('../data/benchmark.json'),fetch('../data/lumiere-0702a05/benchmark.json')]);if(responses.some(r=>!r.ok))throw Error('Dataset unavailable');const [old,fresh]=await Promise.all(responses.map(r=>r.json()));rows=combine(old,fresh);ready=true;render()}catch(e){$('status').textContent='[ERROR] Could not load the saved data. Reload or open the original report in “Read the data”.';$('status').setAttribute('role','alert');console.error(e)}
